package entities;

public enum EntitiesStates {

    /* PASSENGER STATES */
    AT_THE_DISEMBARKING_ZONE,
    AT_THE_LUGGAGE_COLLECTION_POINT,
    EXITING_THE_ARRIVAL_TERMINAL,
    AT_THE_BAGGAGE_RECLAIM_OFFICE,
    AT_THE_ARRIVAL_TRANSFER_TERMINAL,
    TERMINAL_TRANSFER,
    AT_THE_DEPARTURE_TRANSFER_TERMINAL,
    ENTERING_THE_DEPARTURE_TERMINAL,

    /* PORTER */
    WAITING_FOR_A_PLANE_TO_LAND,
    AT_THE_PLANES_HOLD,
    AT_THE_LUGGAGE_BELT_CONVEYOR,
    AT_THE_STOREROOM,

    /* BUS DRIVER STATES */
    PARKING_AT_THE_ARRIVAL_TERMINAL,
    DRIVING_FORWARD,
    PARKING_AT_THE_DEPARTURE_TERMINAL,
    DRIVING_BACKWARD
}
